---
title: "Read in KML"
author: "Justin Williams"
date: "4/12/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages}
library(tidyverse)
library(sf)
library(here)
library(RSelenium)
```

## Overview

This notebook will read in KML file and clean it for processing in the `sf` simple features demo for R

```{r}
if (FALSE) {
# start a chrome browser
rD <- rsDriver(browser = c("chrome"))
remDr <- rD[["client"]]
remDr$open()
remDr$navigate("https://www.google.com/maps/d/u/0/viewer?mid=1fqTOVOwP6fj4NXOpFHT2Y48e3zEghRiJ&ll=40.760619747874316%2C-73.98352704302141&z=11")

ellipsis_element <- remDr$findElement(using = "class", value = "mU4ghb-xl07Ob-LgbsSe-Bz112c HzV7m-tJHJj-LgbsSe-Bz112c")

ellipsis_element$clickElement()

dl_kml_element <- remDr$findElement(using = "class",
                                    value = "j07h3c")
dl_kml_element$clickElement()

ok_element <- remDr$findElement(using = "class",
                                value = "RveJvd snByac")
ok_element$clickElement()

remDr$close()
# stop the selenium server
rD[["server"]]$stop()

# if user forgets to stop server it will be garbage collected.
rD <- rsDriver()
rm(rD)
gc(rD)
}

```


## Load in data

```{r load-kml}
green_markets <- read_sf(here::here("./data/GrowNYC Schedule & Map.kml"))
```

## Get attributes

```{r get-attributes}

green_markets <- green_markets %>% 
  separate(Description,
           into = c("location", "day", "duration",
                    "compost_hours", "coordinates", "webpage"),
           sep = "<br>") %>% 
  mutate(longitude = st_coordinates(geometry)[,1],
         latitude = st_coordinates(geometry)[,2]) %>%
  st_drop_geometry() %>% 
  subset(select = -c(coordinates))

```

```{r create-type-column}
(green_markets <- green_markets %>% 
  mutate(type = case_when(
    grepl("Greenmarket",Name) ~ "Greenmarket",
    grepl("Fresh Food Box",Name) ~ "Fresh Food Box",
    grepl("Food Scrap Drop-off",Name) ~ "Food Scrap Drop-off",
    grepl("BronxWorks",Name) | grepl("Farmstand",Name) ~ "Farmstand",
    grepl("Community Farm", Name) ~ "Community Farm")))
```

Strip away excess.

```{r strip-away-excess}
(green_markets <- green_markets %>%
  mutate(across(location:webpage, ~ gsub(".*:\\s","",.))) %>% 
  mutate(Name = str_remove(Name, "Compost at")) %>% 
  select(Name, type, everything()))
```

Next thing to do could be separate Compost hours time into start and end time columns. 

```{r save-rds}
saveRDS(green_markets, "./data/green_markets")
```


